### ISSUE TITLE
The right way to delete an imodel in iModelHub?

### ISSUE THREAD

**Issue by XinJack** [imodeljs/iModelJs-docs-output#1]
I was able to create an imodel in iModelHub, however, when I tried to delete an imodel in iModelHub, some error is thrown and **it seems to be concerned with the accessToken** (which I think it's ok because I can get the remote imodel with the same token). So I wonder what's the right way to delete an imodel in iModelHub.
  The codes below is how I attempted to delete an imodel in iModelHub.
![delete1](https://user-images.githubusercontent.com/19924871/41274194-27c505b6-6e4f-11e8-97ad-a6fd8c2be559.PNG)
![delete2](https://user-images.githubusercontent.com/19924871/41274196-2c754792-6e4f-11e8-9524-761100d7096a.PNG)
   And the error message is:
![delete3](https://user-images.githubusercontent.com/19924871/41274253-5ae67894-6e4f-11e8-9957-1975b0eec64e.PNG)

**Comment by ramanujam-raman** [comment]
Do you have this environment set? 
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; 
Not sure if this is the problem since it would have likely caused the creation to fail as well.

**Comment by Animagne** [comment]
If you are writing an application or testing how code works, it is recommended to use QA environment. QA has a proper certificate and wouldn't need any workarounds. DEV is meant primarily for iModel Hub developers and to test new features.

**Comment by XinJack** [comment]
Changing from DEV environment to QA environment did help solve this problem. That's a lot. :-) @Animagne
